### ISSUE TITLE
[Wii] [GX] 240p display mode support

### ISSUE THREAD

**Issue by Cavalry2010** [Mefiresu/RSDKv5-Decompilation#11]
Hi! I'm wondering if it could be possible to add a 240p display mode for us CRT users?
Thank you for porting this to the Wii!

**Comment by Mefiresu** [comment]
This is definitely possible, and is already planned.
It will likely have to be enabled through Settings.ini with a special flag.

**Comment by ristar8** [comment]
Does the Sonic CD port have a 240p feature and what special flag?

**Comment by Mefiresu** [comment]
I'm not the author of the Sonic CD port so I'd say no.
The flag isn't implemented yet, but I'm thinking of adding something like `240pMode=y`.

**Comment by ristar8** [comment]
Do you think you can implement it in the next update and also can you also add a 4:3 mode. I remember Sonic mania has an built in 4:3 mode on PC. Also if this is for retro engine do you plan on porting CD, 1, and 2 sometime in the future?

**Comment by Mefiresu** [comment]
I do this is my spare time, and 240p is kind of a niche use case, so it's at the bottom of my priority list.
4:3 mode is already available, you need to put your Wii in 4:3 in the System Settings (which you should have done already if you're playing on a CRT anyway).
CD, 1 and 2 will be playable using RSDKv5U after some bug fixes, no ETA on that. I don't plan to port the other retro engine versions (ports have been made already, so there's no point in doing it again).

**Comment by niuus** [comment]
>4:3 mode is already available, you need to put your Wii in 4:3 in the System Settings (which you should have done already if you're playing on a CRT anyway)

Kind request: can 4:3 / 16:9 be changed through the ini? I have my TV setup with a Wii and the System Settings in 16:9, though emulators and other apps give me the option to use it with the aspect ratio corrected, and when they don't, I just quickly flick it using the TV remote. Having the option through the System Settings means having to switch it only to enjoy Mania at 4:3. If you don't want to do it, it's fine, just to be clear. Thanks for the port, I have been enjoying it a lot, Mania on the Wii is a match made in 2D heaven.

**Comment by Mefiresu** [comment]
Done in PR #17.
