### ISSUE TITLE
[Wii] [GX] Stardust Speedway Act 2 Boss Slowdown

### ISSUE THREAD

**Issue by MegaBlue92** [Mefiresu/RSDKv5-Decompilation#14]
Starts to slowdown during the Metal Sonic fight. Assuming it's that 3D rotating Robotnik statue in the background. Don't know if it's possible but maybe removing that from the background could help. Almost done with game and so far it's a pretty good port and look forward to future updates.

**Comment by Mefiresu** [comment]
Related to #10, will be fixed with the 3D renderer.
