### ISSUE TITLE
Stardust Speedway Act 2 immediately crashes

### ISSUE THREAD

**Issue by withered-rose** [Mefiresu/RSDKv5-Decompilation#16]
After ending Stardust Speedway Act 1, the transitionary cutscene to Act 2 plays out as normal. After the cutscene finishes, though, the game crashes before Act 2 is able to start. This also happens when the cutscene is skipped.
![Screenshot 2022-11-05 22-43-00](https://user-images.githubusercontent.com/10931817/200151583-78e94d21-e033-4ab8-b49d-5ede609b0587.png)

https://user-images.githubusercontent.com/10931817/200151642-9417cee1-60b7-49a7-9da5-8a0ba52984e0.mp4

**Comment by Mefiresu** [comment]
Fixed in 0f34bb8
