### ISSUE TITLE
Black Screen when using v.5 and using the new directories.

### ISSUE THREAD

**Issue by Cavalry2010** [Mefiresu/RSDKv5-Decompilation#27]
I just downloaded the new release and installed it on my Wii following the instructions (/RDSKv5/<GameName>/Data.rdsk), but when loading them from the HBC it just turns into a black screen and I have to hard reset the Wii. This happens on all Sonic Games (1, 2, CD and Mania) and I tried from SD and USB. However I tried loading the "boot.dol" file from WiiXplorer and it results in a blue window with the message "Mod load complete" or something like that but it just hangs there and I have to hard reset the Wii. One last thing that I tried was pasting Mania's Data.rdsk using the old instructions (/RDSKv5/Data.rdsk) and loading the "boot.dol" file from WiiXplorer and it worked! But this only works with Mania. I tried the same thing with Sonic 1, 2 and CD with their respective Data.rdsk files and it just froze in the "Mod load complete" screen.

**Comment by Mefiresu** [comment]
The new version adds a custom path argument that is given in meta.xml. WiiXplorer ignores it, and defaults to `/RSDKv5/`.
Please move the Data.rsdk files to their respective folder.

**Comment by Loveshock** [comment]
Hi, adding onto this just to say that the black screen issue occurs on V0.5 as well.
Loading via SD card and the Homebrew Channel results in a black screen that requires a hard reset of the system.
Data.rsdk files are in their respective folders.
Tested with Mania, 1, and 2.

**Comment by Mefiresu** [comment]
It seems to be an issue with the release build...

**Comment by Deotex2** [comment]
Where did v5 go? its now gone its now just the broken v4 one. when will v5 be back?

**Comment by Fancy2209** [comment]
> Where did v5 go? its now gone its now just the broken v4 one. when will v5 be back?

v4 works. v5 will be back when it works instead of black screening without plus.

**Comment by Mefiresu** [comment]
[v0.5.0](https://github.com/Mefiresu/RSDKv5-Decompilation/releases/tag/v0.5.0) has been rereleased and should now work properly.
