### ISSUE TITLE
Adding mods

### ISSUE THREAD

**Issue by Deotex2** [Mefiresu/RSDKv5-Decompilation#28]
I have no idea how to add mods. I'm trying to add no decoration special stage but I don't know how to add it. Can you please help.

**Comment by Mefiresu** [comment]
Ask over on the REMS discord server: https://dc.railgun.works/retroengine

**Comment by Deotex2** [comment]
Whats your name over there and why can't you just tell me here

**Comment by Deotex2** [comment]
I dont even know where to ask. It says on the release to add no decoration special stage mod to make special stages run better but there is no tutorial how to do so. Do you even know how to add mods.

**Comment by Mefiresu** [comment]
GitHub issues are for bug reports (specifically for the v5 Wii port), not general support.
Discord is more convenient for this.

**Comment by Deotex2** [comment]
I just want to know how to add the no decorations mod for the wii not the pc version its in the description for the release. You must know how to add mods for this wii version just tell me how. I'm not looking for general support.

**Comment by zeeblox09** [comment]
> I just want to know how to add the no decorations mod for the wii not the pc version its in the description for the release. You must know how to add mods for this wii version just tell me how. I'm not looking for general support.
> 
> Edit: Got it working thanks.

hey sorry for the notification to a 2 year old thread but i'm having the same issue
can you tell me too please? :D
