### ISSUE TITLE
sonic 1,2,cd

### ISSUE THREAD

**Issue by zonalmateusgg471** [Mefiresu/RSDKv5-Decompilation#30]
Não sei mas o sonic 1,2,cd estão travando na tela de carregamento quando eu inicio o boot do programa o Console não corresponde os comandos fazendo eu desliga-o da tomada, não sei se e os data.rsdk que está errado.

**Comment by saulfabregwiivc** [comment]
Same issue here.

Translation:
I don't know but Sonic 1,2,CD are stuck on the loading screen when I start the program boot the Console doesn't detect any input/command making me unplug it from the socket, I don't know if it's the data.rsdk that's wrong.

**Comment by CrashMidnick** [comment]
Same here, I tried different versions but I am stuck on that blue screen.

**Comment by nerd-zip** [comment]
me three :(

**Comment by HyperLink-YT** [comment]
I think it requires the Sonic Origins' versions of the Data.rsdk files labelled Sonic1u.rsdk, Sonic2u.rsdk, and SonicCDu.rsdk. Sonic Origins uses modified versions that run in RSDKv5U instead of RSDKv4. Data.rsdk files from RSDKv4 won't work in RSDKv5U without modification, which is why they tricked the game into thinking it was RSDKv5U. I don't even know how they did it, but it's pretty cool.

**Comment by nerd-zip** [comment]
Would these files possibly be obtainable from the Xbox version? Or would you happen to know of a Totally Legal way of obtaining the Origins specific ones?

**Comment by nerd-zip** [comment]
Can confirm, you can use the Yuzu emulator to get the files from a "dumped" Sonic Origins .nsp, but in the FAQ it does state you have to provide your own sound files for it

**Comment by BonQerss** [comment]
can confirm this isn't true. same exact issue even loading with the sonic origins .rdsk

**Comment by nerd-zip** [comment]
Sorry if this is a dumb question, but have you tried renaming each Data file to simply "Data.rsdk"?

**Comment by zonalmateusgg471** [comment]
Sim fiz isso botei data.rsdk mas o bot do jogo não reconhece o data do data aí ele trava

**Comment by MilesTailsFan2005** [comment]
It Requires Origins Just Need Sonic 3 To Complete The Collection 
https://store.steampowered.com/app/1794960/Sonic_Origins/
Just Buy The Base You Don't Need The Plus DLC You Will Not Get Character Selections Like In Origins For Sonic 1 2 And CD
