### ISSUE TITLE
Got Sound Working 

### ISSUE THREAD

**Issue by MilesTailsFan2005** [Mefiresu/RSDKv5-Decompilation#34]
Hey soo...I got Sound Working on the S1 RSDK Right now only music is working

But I would love to show it but I can't upload the data.rsdk this requires sonic 1 2013, sonic origins data.rsdk and mania RSDK5 extracter and repacker by main memory

**Comment by BonQerss** [comment]
Not entirely positive about music, I repacked the game with the music files from the base game and got it to work. SoundFX won't work if you do that though, you'll need this mod: https://gamebanana.com/mods/441458
Doesn't work perfectly, can't get it to work for Sonic CD, enabling it in Sonic 1 changes the lives icon to Amy, and enabling it in Sonic 1 enables & Tails but locks all inputs. Hopefully someone finds a full solution.
