### ISSUE TITLE
Audio Isn't Working

### ISSUE THREAD

**Issue by MysteryWood** [Mefiresu/RSDKv5-Decompilation#36]
Audio isn't working in Sonic 1, 2 and CD. I'm using origins data.rsdk for those games cause the mobile wont work for sonic 1&2 and the steam one wont work on CD

**Comment by Mefiresu** [comment]
There's no audio in the Origins RSDK datafiles.

**Comment by MysteryWood** [comment]
still doesn't work even when rebuilding
