### ISSUE TITLE
[3DS] Having issues compilling it

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Mefiresu/RSDKv5-Decompilation#52]
```
RSDKv53DS on  dev/3ds-rebase via △ v3.28.2 took 4s 
 ❯ cmake --build build --config release
[  3%] Building CXX object CMakeFiles/RetroEngine.dir/RSDKv5/main.cpp.o
Dans le fichier inclus depuis /home/pm/Documents/RSDKv53DS/RSDKv5/main.cpp:1:
/home/pm/Documents/RSDKv53DS/RSDKv5/RSDK/Core/RetroEngine.hpp:575:10: erreur fatale: SDL.h : Aucun fichier ou dossier de ce nom
  575 | #include "SDL.h"
      |          ^~~~~~~
compilation terminée.
gmake[2]: *** [CMakeFiles/RetroEngine.dir/build.make:76: CMakeFiles/RetroEngine.dir/RSDKv5/main.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/RetroEngine.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```
I'm having issues compiling the 3DS branch despite having the normally, right SDL devel bits installed, after successfully compiling your Wii main branch, and upstream main repo Linux build for my desktop PC.
All the noted dependencies are installed and fine, on my Fedora 40 machine.

**Comment by Mefiresu** [comment]
The 3DS port doesn't use SDL at all, make sure you're using the 3DS cmake toolchain file.
Example:
```sh
cmake -B build -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/3DS.cmake
cmake --build build
```
Also it seems that you only have RSDKv5, make sure to clone the [https://github.com/RSDKModding/Sonic-Mania-Decompilation](mania repo) and either change the RSDKv5 submodule to mine or add `-DRSDK_PATH=/path/to/RSDKv5` to the first cmake command.
